### PR TITLE
Increase default buffer size

### PR DESCRIPTION
**Pull request by StephenHynes7**
Increase the default buffer size from 100 to 32768

### CODE REVIEW

**Comment by bathos** [comment]
That is quite large -- are you sure about this? This is not a byte buffer, it is buffer of objects. 1 item is 1 log entry. The le_node default is already an order of magnitude above the default object stream high water mark, which is 10. With a setting this high, if the connection drops, it becomes plausible that le_node could become a resource sink.

**Comment by StephenHynes7** [comment]
@bathos What could go wrong :) The majority of our libs have queues of this size, ideally with a robust reconnection algorithm we never get close to fill this. The fact is at the moment that in many scenarios we fill the buffer instantly and the application fails which is not nice, boosting it should solve some of these problems but of course there is a trade of in terms of performance of the lib in the worst case scenario.

**Comment by bathos** [comment]
I think the distinction of note here is that in nodeland, people are almost always logging objects, which is what this stream is configured for. These objects, in turn, are typically "throw away" literals to which no other reference will exist, like `logger.info({ x, y, z  })`. Staying with the typical scenario, the user doesn't expect these objects to be long-lived, so the objects may or may not be expensive to hold onto.

That said, they probably *won't* be expensive. Most of them will be very simple and light, so there's a case to be made for going up to 1000, 5000, whatever -- but the higher you go, the higher the risk of creating a memory leak. For a real world example, let's say a user is logging raw request or response objects (if the github issues are instructive, although this is a bad idea, it is something people really do). Those are massive, deep and circular objects, so I'm pretty sure holding onto 33,000 of them in a buffer would have consequences.

If you think this is wise, by all means, go for it, I just wanted to make sure you knew it was an object count. The number, 32768, made me think you might have thought it was a byte size.

**Comment by stopal-r7** [comment]
this should be fixed with ring buffer implementation.

**Pull request closed without merging**
